name: Build LaTeX document
on:
  push:
    paths:
      - 'docs/**'
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install TeX Live and biber
        run: sudo apt-get update && sudo apt-get install -y texlive-full biber

      - name: Compile LaTeX document (first run)
        working-directory: docs
        run: |
          latexmk -lualatex -interaction=nonstopmode main.tex

      - name: Run biber for bibliography
        working-directory: docs
        run: biber main

      - name: Compile LaTeX document (second run)
        working-directory: docs
        run: |
          latexmk -lualatex -interaction=nonstopmode main.tex
          latexmk -lualatex -interaction=nonstopmode main.tex

      - name: Push PDF to GitHub
        working-directory: docs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add main.pdf
          git commit -m "@actions: update PDF"
          git push
