name: Build LaTeX document
on: 
  push:
    paths:
      - 'docs/**'
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: docs
          latexmk_use_lualatex: true
          args: "-lualatex -file-line-error -interaction=nonstopmode"
      - name: Push PDF to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/main.pdf
          git commit -m "@actions: update PDF"
          git push
